name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-24.04

    services:
      mariadb:
        image: mariadb:11.8
        env:
          MARIADB_ROOT_PASSWORD: Password123!
          MARIADB_DATABASE: test

        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          curl -LsSO https://r.mariadb.com/downloads/mariadb_repo_setup
          echo "c4a0f3dade02c51a6a28ca3609a13d7a0f8910cccbb90935a2f218454d3a914a  mariadb_repo_setup" | sha256sum -c -
          chmod +x mariadb_repo_setup
          sudo ./mariadb_repo_setup --mariadb-server-version="mariadb-11.8"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            python3-dev \
            libmariadb3 \
            libmariadb-dev \
            pkg-config

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest tests/test_server.py -v
        env:
          # Environment variables for MCP server
          MARIADB_HOST: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_USER: root
          MARIADB_PASSWORD: Password123!
          MARIADB_DATABASE: test
          EMBEDDING_PROVIDER: test
